repos:
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.269  # You can check the latest version on GitHub or PyPI
    hooks:
      - id: checkov
        name: Checkov IaC Scan
        entry: checkov -d ./terraform
        # language: python
        # types: [terraform, yaml, json]  # Specify the file types to scan
        # files: ^(.*\.(tf|json|yaml|yml))$
        args: ["--output", "json"]  # Use json output format
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.1
    hooks:
      - id: gitleaks
