repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.0
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        # entry: gitleaks protect --verbose --redact --staged
        # entry: zricethezav/gitleaks protect --verbose --redact --staged
        # entry: gitleaks detect  --verbose --source ./backend  --report-path gitleaks-report.json
        entry: gitleaks detect --verbose

        # language: node
        # args: ["--verbose", "--source=./backend"]


