# - repo: local
#     hooks:
#       - id: sonar-scanner-frontend
#         name: SonarQube Scanner (frontend)
#         entry: |
#           sonar-scanner -Dsonar.projectKey=frontend -Dsonar.sources=./frontend -Dsonar.host.url=http://sonar.adnovumlabs.com:9900 -Dsonar.login=sqa_66e8f525a41037e7bd1b808c407aedbd5a2e2d87
#         language: system
#         files: frontend
#         pass_filenames: false  # SonarQube works on the entire project, not individual files
#         stages: [pre-commit]

# - repo: local
#   hooks:
#     - id: sonar-scanner-frontend
#       name: SonarQube Scanner (frontend)
#       entry: |
#         sonar-scanner \
#           -Dsonar.projectKey=frontend \
#           -Dsonar.sources=./frontend \
#           -Dsonar.host.url=http://sonar.adnovumlabs.com:9900 \
#           -Dsonar.login=ssss
#       language: system
#       files: frontend
#       pass_filenames: false  # SonarQube works on the entire project, not individual files
#       stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: sonar-scanner-frontend
        name: SonarQube Scanner (frontend)
        entry: |
          sonar-scanner \
            -Dsonar.projectKey=frontend \
            -Dsonar.sources=./frontend \
            -Dsonar.host.url=http://sonar.adnovumlabs.com:9900 \
            -Dsonar.login=ssss
        language: system
        files: frontend
        pass_filenames: false  # SonarQube works on the entire project, not individual files
        stages: [pre-commit]

      # - id: sonar-scanner-terraform
      #   name: SonarQube Scanner (terraform)
      #   entry: |
      #     sonar-scanner -Dsonar.projectKey=terraform -Dsonar.sources=./terraform -Dsonar.host.url=http://sonar.adnovumlabs.com:9900 -Dsonar.login=sqa_66e8f525a41037e7bd1b808c407aedbd5a2e2d87 -Dsonar.language=tf
      #   language: system
      #   files: terraform
      #   pass_filenames: false  # SonarQube works on the entire project, not individual files
      #   stages: [pre-commit]
      # - id: owasp-dependency-check
      #   name: OWASP Dependency Check
      #   entry: dependency-check
      #   language: system
      #   args:
      #     - --scan=.
      #     - --format=ALL
      #   pass_filenames: false  # Runs on the entire project
      #   stages: [commit]
