apiVersion: v1
kind: ConfigMap
metadata:
  name: ps-background-config
  namespace: ps
data:
  DB_SERVER: ps-database-service
  JWT_SECRET: 'testwebapp123'
  POSTGRES_DB: webapp
  POSTGRES_USER: 'admin'
  DB_PORT: '5432'
  PORT: '5002'
