apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-frontend
  namespace: ps
  labels:
    app: ps-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ps-frontend
  template:
    metadata:
      labels:
        app: ps-frontend
    spec:
      containers:
        - name: ps-frontend
          image: makwanji/webapp-front:v0.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          env:
            - name: TZ
              value: "Asia/Singapore"
            - name: REACT_APP_API_URL
              value: "https://psdemo.adnovumlabs.com:5001"
          # envFrom:
          #   - secretRef:
          #       name: {{ .Values.config.secret }}