apiVersion: v1
kind: Service
metadata:
  name: ps-frontend-service
  namespace: ps
  labels:
    app: ps-frontend
spec:
  selector:
    app: ps-frontend
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
