sonar.genericIssues.reportPaths=sonarqube_report.json
sonar.projectKey=terraform
sonar.sources=.
sonar.host.url=http://sonar.adnovumlabs.com:9900
sonar.token=sqa_66e8f525a41037e7bd1b808c407aedbd5a2e2d87
sonar.python.version=3.8
# sonar.externalIssuesReportPaths=sonarqube_report.json
# sonar.externalIssuesReportPaths=terrascan.json
sonar.externalIssuesReportPaths=g2sonar-issues.json
# sonar.checkov.reportFiles=checkov_report.json
# sonar.externalIssuesReportPaths=sonarqube_report.json

