name: DevSecOps CI (ProductService - API)

on:
  push:
    branches:
      - main  # You can change this to the branch where you want the action to trigger
      - draft
    paths:
      - 'backend/**'  # Triggers only if there are changes in the 'productservice-webse' subfolder
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: cd backend && npm ci && cd .. # npm ci

      - name: Build application
        run: exit 0 # npm run build

      # Run ESLint or other static analysis tool
      - name: Run ESLint [syntax errors, code quality issues, and enforcing coding standards]
        run: cd backend && npm install && npx eslint . && cd ..

  sast:
    name: SAST - Static Code Analysis
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: SonarQube Scan
      #   run: exit 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          # projectBaseDir: backend
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          args: >
            -Dsonar.projectKey=backend
            -Dsonar.sources=backend

  dep-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: cd backend && npm ci && cd ..

      # Check for vulnerabilities in node_modules using npm audit
      - name: Check for vulnerable packages using npm audit
        run: cd backend && npm audit --audit-level=high && cd ..

      # - name: OWASP Dependency Check
      #   run: exit 0

      # OWASP Dependency-Check scan for vulnerabilities
      - name: OWASP Dependency Check
        id: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'ProductServiceAPI'
          format: 'HTML'
          out: './dependency-check-report'
          path: './backend'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload dependency check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report/dependency-check-report.html

  test:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest
    needs:
      - sast
      - dep-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # - name: Install dependencies
      #   run: npm ci

      # - name: Run tests
      #   run: npm test

      - name: Run tests
        run: exit 0

  docker:
    name: Build, Scan and Publish Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: cd backend && npm ci && cd ..

      - name: Build application
        run: exit 0 #cd backend && npm run build && cd ..

      # Dockerize the app using multi-stage build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      # Step 2: Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Log in to AWS ECR
      - name: Log in to Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build Docker image
        run: |
          docker build --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
                       --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
                       --build-arg POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
                       -t productservice-app:v1.0.${{ github.run_number }} ./backend # Build from the 'backend' subfolder

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'productservice-app:v1.0.${{ github.run_number }}'
          ignore-unfixed: true
          vuln-type: 'os,library'
          trivy-config: trivy.yaml
          scan-type: image

      - name: Tag Docker image
        run: |
          docker tag productservice-app:v1.0.${{ github.run_number }} ${{ secrets.ECR_REPOSITORY_URI }}/productservice-app:v1.0.${{ github.run_number }}

      # Step 8: Push the Docker image to AWS ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/productservice-app:v1.0.${{ github.run_number }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to Kubernetes cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          exit 0 # kubectl apply -f k8s/deployment.yaml

