name: KBOM Security Checks

on:
  push:
    branches:
      - main
      - draft
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Update kube config
      #   run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Download KBOM Artifact
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: kbom

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'
      - name: Check install!
        run: cosign version

      # - name: Download cosign
      #   env:
      #     COSIGN_EXPERIMENTAL: "1"
      #   run: |
      #     curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign
      #     chmod +x /usr/local/bin/cosign

      - name: Verify Signature
        continue-on-error: true
        run: |
          cosign verify --key ${{ secrets.COSIGN_KEY_PATH }} kbom.json > signature_verification.txt

      - name: send notification if Signature failed
        run: |
          echo "send notification"
          exit 0

      - name: Upload Signature Verification Report
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: signature-verification-report
          path: signature_verification.txt


  generate_sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.56.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: kube config list
        run: kubectl config get-contexts

      - name: Generate KBOM Artifact
        run: |
          trivy k8s arn:aws:eks:***:851725219470:cluster/${{ secrets.EKS_CLUSTER_NAME }} --scanners vuln --report summary --disable-node-collector > kbom.json

      - name: Save KBOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kbom
          path: kbom.json

  # vulnerability_scan:
  #   name: Vulnerability Scan
  #   runs-on: ubuntu-latest
  #   needs: generate_kbom
  #   steps:
  #     - name: Download KBOM Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: kbom

  #     - name: Scan for Vulnerabilities with Trivy
  #       run: |
  #         curl -sfL https://aquasecurity.github.io/trivy-repo/install.sh | sh -s -- -b /usr/local/bin
  #         trivy image --input kbom.json --severity CRITICAL,HIGH > vulnerability_report.txt

  #     - name: Upload Vulnerability Report
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: vulnerability-report
  #         path: vulnerability_report.txt

  # misconfiguration_detection:
  #   name: Misconfiguration Detection
  #   runs-on: ubuntu-latest
  #   needs: generate_kbom
  #   steps:
  #     - name: Download KBOM Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: kbom

  #     - name: Lint KBOM with Spectral
  #       run: |
  #         curl -sSfL https://github.com/stoplightio/spectral/releases/download/v6.0.0/spectral-linux -o /usr/local/bin/spectral
  #         chmod +x /usr/local/bin/spectral
  #         spectral lint kbom.json --ruleset https://example.com/path/to/your-ruleset.yaml > misconfig_report.txt

  #     - name: Upload Misconfiguration Report
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: misconfiguration-report
  #         path: misconfig_report.txt

  # signature_verification:
  #   name: Signature Verification
  #   runs-on: ubuntu-latest
  #   needs: generate_kbom
  #   steps:
  #     - name: Download KBOM Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: kbom

  #     - name: Sign KBOM with Cosign
  #       env:
  #         COSIGN_EXPERIMENTAL: "1"
  #       run: |
  #         curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign
  #         chmod +x /usr/local/bin/cosign
  #         cosign sign -key ${{ secrets.COSIGN_KEY_PATH }} kbom.json > signature.txt

  #     - name: Verify Signature
  #       run: |
  #         cosign verify -key ${{ secrets.COSIGN_KEY_PATH }} kbom.json > signature_verification.txt

  #     - name: Upload Signature Verification Report
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: signature-verification-report
  #         path: signature_verification.txt

  # compliance_audit:
  #   name: Compliance Audit
  #   runs-on: ubuntu-latest
  #   needs: [generate_kbom, vulnerability_scan, misconfiguration_detection, signature_verification]
  #   steps:
  #     - name: Download All Reports
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: vulnerability-report
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: misconfiguration-report
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: signature-verification-report

  #     - name: Aggregate and Upload Compliance Report
  #       run: |
  #         cat vulnerability_report.txt > compliance_report.txt
  #         echo "---" >> compliance_report.txt
  #         cat misconfig_report.txt >> compliance_report.txt
  #         echo "---" >> compliance_report.txt
  #         cat signature_verification.txt >> compliance_report.txt

  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: compliance-report
  #         path: compliance_report.txt

  #     - name: Notify Team (Optional)
  #       if: failure()
  #       uses: slackapi/slack-github-action@v1.23.0
  #       with:
  #         channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
  #         slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
  #         text: |
  #           KBOM Compliance Check Failed. Please review the compliance report.
