name: sonar-test

on:
  push:
    branches:
      - main  # You can change this to the branch where you want the action to trigger
      - draft
    paths:
      - 'backend/**'  # Triggers only if there are changes in the 'productservice-webse' subfolder
  workflow_dispatch:

jobs:
  sasttest:
    name: SAST - Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: SonarQube Scan
      #   run: exit 0

      - name: SonarQube Scan
        id: bg_stat
        # run: exit 0
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          # projectBaseDir: backend
          # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          args: >
            -Dsonar.projectKey=backend
            -Dsonar.sources=backend
            -Dsonar.host.url=http://sonar.adnovumlabs.com:9900
            -Dsonar.token=sqp_31fa610082cc3f40f57d24c12bece969888ce501

# sonar-scanner \
#   -Dsonar.projectKey=backend \
#   -Dsonar.sources=backend \
#   -Dsonar.host.url=http://sonar.adnovumlabs.com:9900 \
#   -Dsonar.token=sqp_31fa610082cc3f40f57d24c12bece969888ce501
