name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - draft
    paths:
      - 'terraform/**'  # Triggers only if there are changes in the 'terraform' subfolder
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0  # Specify your Terraform version here

      # Step 3: Run Terraform format
      - name: Terraform Format
        run: terraform fmt -check

      # Step 4: Run Terraform lint (optional)
      - name: Terraform Lint
        run: terraform init && tflint

      # Step 5: Run Terraform plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # # Step 6: Manual Approval Step
      # - name: Request Approval
      #   id: approval
      #   uses: rymes/approval-action@v1
      #   with:
      #     approvers: "makwanji"  # Specify approvers
      #     comment: "Terraform plan is ready for approval."

      # Step 7: Terraform Apply (only if approved)
      - name: Terraform Apply
        # if: steps.approval.outputs.approved == 'true'
        run: terraform apply -auto-approve tfplan

      # Step 8: Cleanup (optional)
      - name: Cleanup
        run: terraform workspace select default && terraform workspace delete -force non-production
